In [1]:
import pandas as pd
import numpy as np


from bs4 import BeautifulSoup
import requests
import world_bank_data as wb

In [2]:
carsdf = pd.read_csv("./vehicles.csv")
carsdf.head(10)

cleaneddf=carsdf.fillna("filled")
#carsdf.columns
#carsdf[carsdf.columns[10:20]]
#carsdf[carsdf.columns[70:80]]
cleaneddf
dfcars_selection = carsdf[["make","id","model","fuelType","fuelType1","fuelType2","evMotor", "cityE","co2","co2TailpipeAGpm","co2TailpipeGpm","comb08", "combA08", "combE","highway08","highwayA08","highwayE","UCity","UCityA","UHighway","UHighwayA" ]]

c:\users\xico2\appdata\local\programs\python\python37-32\lib\site-packages\IPython\core\interactiveshell.py:3146: DtypeWarning: Columns (70,71,72,73,74,76,79) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [3]:
dfselection = cleaneddf[["make","id","model","year","fuelType","evMotor","cityE","co2","co2TailpipeGpm","comb08", "combE","highway08","highwayE","UCity","UHighway"]]
dfselection[dfselection["fuelType"]=="Electricity"][["make","model"]]

         make                              model
7138   Nissan                           Altra EV
7139   Toyota                            RAV4 EV
8143   Toyota                            RAV4 EV
8144     Ford                              Th!nk
8146     Ford             Explorer USPS Electric
...       ...                                ...
36719   Tesla  Model X Performance (22in Wheels)
36720   Tesla             Model Y Long Range AWD
36721   Tesla            Model Y Performance AWD
36727     Kia                      Soul Electric
36728   Tesla            Model X Long Range Plus

[252 rows x 2 columns]

In [4]:
dfselection[dfselection["fuelType"]=="Electricity"]

,make,id,model,year,fuelType,evMotor,cityE,co2,co2TailpipeGpm,comb08,combE,highway08,highwayE,UCity,UHighway
7138,Nissan,16423,Altra EV,2000,Electricity,62 KW AC Induction,41.0000,0,0.0,85,40.0000,91,37.0000,116.2069,129.6154
7139,Toyota,16424,RAV4 EV,2000,Electricity,50 KW DC,41.0000,0,0.0,72,47.0000,64,53.0000,116.2069,91.0811
8143,Toyota,17328,RAV4 EV,2001,Electricity,50 KW DC,41.0000,0,0.0,72,47.0000,64,53.0000,116.2069,91.0811
8144,Ford,17329,Th!nk,2001,Electricity,27 KW AC Induction,46.0000,0,0.0,65,52.0000,58,59.0000,105.3125,82.1951
8146,Ford,17330,Explorer USPS Electric,2001,Electricity,67 KW AC Induction,75.0000,0,0.0,39,87.0000,33,102.0000,62.4074,46.8056
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36719,Tesla,43405,Model X Performance (22in Wheels),2021,Electricity,151 and 273 kW AC 3-Phase,38.0795,0,0.0,86,39.2815,83,40.7505,119.0000,111.2000
36720,Tesla,43406,Model Y Long Range AWD,2021,Electricity,69 and 201 kW AC 3-Phase,25.6464,0,0.0,125,27.0455,117,28.7556,171.1000,152.6000
36721,Tesla,43407,Model Y Performance AWD,2021,Electricity,133 and 179 kW AC 3-Phase,29.3322,0,0.0,111,30.4938,106,31.9135,149.6000,137.5000
36727,Kia,43412,Soul Electric,2020,Electricity,201 kW AC PMSM,25.9849,0,0.0,114,29.1732,101,33.0701,185.3000,145.6000
36728,Tesla,43413,Model X Long Range Plus,2020,Electricity,193 and 205 kW AC 3-Phase,31.0865,0,0.0,105,32.1566,101,33.4644,153.4000,142.5000

In [5]:
motortype = dfselection[(dfselection["fuelType"]=="Electricity") & (dfselection["year"]>2018)]["evMotor"].value_counts()
motortype

193 and 205 kW AC 3-Phase                          11
211 kW AC 3-Phase                                   8
147 and 211 kW AC 3-Phase                           5
150 kW ACPM                                         4
160 kW DCPM                                         4
100 kW AC PMSM                                      3
141 and 172 kW Asynchron 3-Phase                    2
193 (front), 205/375 (rear) kW ACPM                 2
135 kW DCPM                                         2
125 kW AC Induction                                 2
193 (front) 193 (rear) (75 kW-hr battery pack)      2
205 and 375 kW AC 3-Phase                           2
110 kW DCPM                                         2
60 KW AC Synchronous                                2
135 kW AC Induction                                 2
151 and 273 kW AC 3-Phase                           2
150 kW IPMSM                                        2
193 (front) 193 (rear) (100 kW-hr battery pack)     2
147 and 188 kW AC 3-Phase                           2
147 and 147 kW AC 3-Phase                           2
193 (front) 375 (rear) (100 kW-hr battery pack)     2
150 kW AC PMSM                                      2
131 and 190 kW AC 3-Phase                           1
82 kW AC Induction                                  1
120 and 170 kW ACPM                                 1
88 kW AC PMSM                                       1
98 and 195 kW AC 3-Phase                            1
133 and 179 kW AC 3-Phase                           1
81 kW AC PMSM                                       1
201 kW AC PMSM                                      1
120 kW AC PMSM                                      1
120 kW ACPM                                         1
193 and 375 kW AC 3-Phase                           1
180 and 189 kW AC 3-Phase                           1
170 kW ACPM                                         1
75 kW DCPM                                          1
158 and 219 kW AC 3-Phase                           1
69 and 201 kW AC 3-Phase                            1
158 and 203 kW AC 3-Phase                           1
Name: evMotor, dtype: int64

In [6]:
model_el_name=dfselection[(dfselection["fuelType"]=="Electricity") & (dfselection["year"]>2018)][["make","model"]]

model_el_name

             make                              model
33394     Hyundai                     Ioniq Electric
33544   Chevrolet                            Bolt EV
33615     Hyundai                      Kona Electric
33818         Kia                      Soul Electric
33819  Volkswagen                             e-Golf
...           ...                                ...
36719       Tesla  Model X Performance (22in Wheels)
36720       Tesla             Model Y Long Range AWD
36721       Tesla            Model Y Performance AWD
36727         Kia                      Soul Electric
36728       Tesla            Model X Long Range Plus

[84 rows x 2 columns]

In [7]:
#model_el_name.to_csv("elec_car_names.csv")

In [8]:

allcars_2018 = dfselection[dfselection["year"]>2018]
allcars_2018

,make,id,model,year,fuelType,evMotor,cityE,co2,co2TailpipeGpm,comb08,combE,highway08,highwayE,UCity,UHighway
32814,Jeep,39861,Cherokee FWD,2019,Midgrade,filled,0.0000,387,387.0,23,0.0000,29,0.0000,24.9000,40.9961
32815,Jeep,39862,Cherokee 4WD,2019,Midgrade,filled,0.0000,400,400.0,22,0.0000,27,0.0000,24.2000,38.8000
32816,Jeep,39863,Cherokee 4WD Active Drive II,2019,Midgrade,filled,0.0000,416,416.0,21,0.0000,26,0.0000,23.1000,37.0483
32817,Jeep,39864,Cherokee Trailhawk 4WD,2019,Midgrade,filled,0.0000,432,432.0,21,0.0000,24,0.0000,22.8996,34.7000
32826,Chevrolet,39872,Corvette,2019,Premium,filled,0.0000,465,465.0,19,0.0000,25,0.0000,20.0270,35.4602
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36723,Lamborghini,43409,Aventador Sian Roadster,2020,Premium,filled,0.0000,861,861.0,10,0.0000,14,0.0000,10.0492,19.1669
36725,Lamborghini,43410,Aventador Sian Coupe,2020,Premium,filled,0.0000,861,861.0,10,0.0000,14,0.0000,10.0492,19.1669
36726,RUF Automobile,43411,TURBO12/CTR3/CTR ANNIVERSARY,2020,Premium,filled,0.0000,497,497.0,18,0.0000,20,0.0000,20.2300,27.6300
36727,Kia,43412,Soul Electric,2020,Electricity,201 kW AC PMSM,25.9849,0,0.0,114,29.1732,101,33.0701,185.3000,145.6000
36728,Tesla,43413,Model X Long Range Plus,2020,Electricity,193 and 205 kW AC 3-Phase,31.0865,0,0.0,105,32.1566,101,33.4644,153.4000,142.5000

In [9]:
# starting formulas calculation



# 1 mile = 1.60934 km
# 1MPG = 0.425144 kilometer per liter
#def mile_to_km(x):
#    x = x*1.60934
#    return x

#allcars_2018["cityE"]=allcars_2018["cityE"]/1.60934 ## alredy executed dont run again

In [10]:
#next column miles to kms co2 column
#allcars_2018["co2"]=allcars_2018["co2"]/1.60934 already done. commented to not rerun

In [11]:
allcars_2018

,make,id,model,year,fuelType,evMotor,cityE,co2,co2TailpipeGpm,comb08,combE,highway08,highwayE,UCity,UHighway
32814,Jeep,39861,Cherokee FWD,2019,Midgrade,filled,0.0000,387,387.0,23,0.0000,29,0.0000,24.9000,40.9961
32815,Jeep,39862,Cherokee 4WD,2019,Midgrade,filled,0.0000,400,400.0,22,0.0000,27,0.0000,24.2000,38.8000
32816,Jeep,39863,Cherokee 4WD Active Drive II,2019,Midgrade,filled,0.0000,416,416.0,21,0.0000,26,0.0000,23.1000,37.0483
32817,Jeep,39864,Cherokee Trailhawk 4WD,2019,Midgrade,filled,0.0000,432,432.0,21,0.0000,24,0.0000,22.8996,34.7000
32826,Chevrolet,39872,Corvette,2019,Premium,filled,0.0000,465,465.0,19,0.0000,25,0.0000,20.0270,35.4602
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36723,Lamborghini,43409,Aventador Sian Roadster,2020,Premium,filled,0.0000,861,861.0,10,0.0000,14,0.0000,10.0492,19.1669
36725,Lamborghini,43410,Aventador Sian Coupe,2020,Premium,filled,0.0000,861,861.0,10,0.0000,14,0.0000,10.0492,19.1669
36726,RUF Automobile,43411,TURBO12/CTR3/CTR ANNIVERSARY,2020,Premium,filled,0.0000,497,497.0,18,0.0000,20,0.0000,20.2300,27.6300
36727,Kia,43412,Soul Electric,2020,Electricity,201 kW AC PMSM,25.9849,0,0.0,114,29.1732,101,33.0701,185.3000,145.6000
36728,Tesla,43413,Model X Long Range Plus,2020,Electricity,193 and 205 kW AC 3-Phase,31.0865,0,0.0,105,32.1566,101,33.4644,153.4000,142.5000

In [12]:
#allcars_2018["co2TailpipeGpm"]=allcars_2018["co2TailpipeGpm"]/1.60934 already done. commented to not rerun

In [13]:
#MPG transform / by 2.3521458
#allcars_2018["comb08"]=allcars_2018["comb08"]/2.3521458 already done. commented to not rerun

In [14]:
#convert in kms
#allcars_2018["combE"]=allcars_2018["combE"]/1.60934 already done. commented to not rerun

In [15]:
#MPG transform
#allcars_2018["highway08"]=allcars_2018["highway08"]/2.3521458 already done. commented to not rerun

In [16]:
#convert in kms
#allcars_2018["highwayE"]=allcars_2018["highwayE"]/1.60934 already done. commented to not rerun

In [17]:
#MPG transform
#allcars_2018["UCity"]=allcars_2018["UCity"]/2.3521458 already done. commented to not rerun

In [18]:
#MPG transform
#allcars_2018["UHighway"]=allcars_2018["UHighway"]/2.3521458 already done. commented to not rerun

In [19]:
allcars_2018

,make,id,model,year,fuelType,evMotor,cityE,co2,co2TailpipeGpm,comb08,combE,highway08,highwayE,UCity,UHighway
32814,Jeep,39861,Cherokee FWD,2019,Midgrade,filled,0.0000,387,387.0,23,0.0000,29,0.0000,24.9000,40.9961
32815,Jeep,39862,Cherokee 4WD,2019,Midgrade,filled,0.0000,400,400.0,22,0.0000,27,0.0000,24.2000,38.8000
32816,Jeep,39863,Cherokee 4WD Active Drive II,2019,Midgrade,filled,0.0000,416,416.0,21,0.0000,26,0.0000,23.1000,37.0483
32817,Jeep,39864,Cherokee Trailhawk 4WD,2019,Midgrade,filled,0.0000,432,432.0,21,0.0000,24,0.0000,22.8996,34.7000
32826,Chevrolet,39872,Corvette,2019,Premium,filled,0.0000,465,465.0,19,0.0000,25,0.0000,20.0270,35.4602
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36723,Lamborghini,43409,Aventador Sian Roadster,2020,Premium,filled,0.0000,861,861.0,10,0.0000,14,0.0000,10.0492,19.1669
36725,Lamborghini,43410,Aventador Sian Coupe,2020,Premium,filled,0.0000,861,861.0,10,0.0000,14,0.0000,10.0492,19.1669
36726,RUF Automobile,43411,TURBO12/CTR3/CTR ANNIVERSARY,2020,Premium,filled,0.0000,497,497.0,18,0.0000,20,0.0000,20.2300,27.6300
36727,Kia,43412,Soul Electric,2020,Electricity,201 kW AC PMSM,25.9849,0,0.0,114,29.1732,101,33.0701,185.3000,145.6000
36728,Tesla,43413,Model X Long Range Plus,2020,Electricity,193 and 205 kW AC 3-Phase,31.0865,0,0.0,105,32.1566,101,33.4644,153.4000,142.5000

In [20]:
#co2 calculation for electric cars

In [21]:

cars2018_c= allcars_2018.rename(columns= {"make":"brand", "id":"id","model":"model","fuelType":"fueltype","cityE" :"City_kwh_100km", "co2": "CO2_gperkm","comb08": "combined_lperkm", "combE": "combined_kwh_100km","highwayE":"highway_kwh_100km","UCity": "City_lperkm","Uhighway":"highway_lperkm" })
cars2018_c

,brand,id,model,year,fueltype,evMotor,City_kwh_100km,CO2_gperkm,co2TailpipeGpm,combined_lperkm,combined_kwh_100km,highway08,highway_kwh_100km,City_lperkm,UHighway
32814,Jeep,39861,Cherokee FWD,2019,Midgrade,filled,0.0000,387,387.0,23,0.0000,29,0.0000,24.9000,40.9961
32815,Jeep,39862,Cherokee 4WD,2019,Midgrade,filled,0.0000,400,400.0,22,0.0000,27,0.0000,24.2000,38.8000
32816,Jeep,39863,Cherokee 4WD Active Drive II,2019,Midgrade,filled,0.0000,416,416.0,21,0.0000,26,0.0000,23.1000,37.0483
32817,Jeep,39864,Cherokee Trailhawk 4WD,2019,Midgrade,filled,0.0000,432,432.0,21,0.0000,24,0.0000,22.8996,34.7000
32826,Chevrolet,39872,Corvette,2019,Premium,filled,0.0000,465,465.0,19,0.0000,25,0.0000,20.0270,35.4602
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36723,Lamborghini,43409,Aventador Sian Roadster,2020,Premium,filled,0.0000,861,861.0,10,0.0000,14,0.0000,10.0492,19.1669
36725,Lamborghini,43410,Aventador Sian Coupe,2020,Premium,filled,0.0000,861,861.0,10,0.0000,14,0.0000,10.0492,19.1669
36726,RUF Automobile,43411,TURBO12/CTR3/CTR ANNIVERSARY,2020,Premium,filled,0.0000,497,497.0,18,0.0000,20,0.0000,20.2300,27.6300
36727,Kia,43412,Soul Electric,2020,Electricity,201 kW AC PMSM,25.9849,0,0.0,114,29.1732,101,33.0701,185.3000,145.6000
36728,Tesla,43413,Model X Long Range Plus,2020,Electricity,193 and 205 kW AC 3-Phase,31.0865,0,0.0,105,32.1566,101,33.4644,153.4000,142.5000

In [22]:
del cars2018_c["co2TailpipeGpm"]
cars2018_c

,brand,id,model,year,fueltype,evMotor,City_kwh_100km,CO2_gperkm,combined_lperkm,combined_kwh_100km,highway08,highway_kwh_100km,City_lperkm,UHighway
32814,Jeep,39861,Cherokee FWD,2019,Midgrade,filled,0.0000,387,23,0.0000,29,0.0000,24.9000,40.9961
32815,Jeep,39862,Cherokee 4WD,2019,Midgrade,filled,0.0000,400,22,0.0000,27,0.0000,24.2000,38.8000
32816,Jeep,39863,Cherokee 4WD Active Drive II,2019,Midgrade,filled,0.0000,416,21,0.0000,26,0.0000,23.1000,37.0483
32817,Jeep,39864,Cherokee Trailhawk 4WD,2019,Midgrade,filled,0.0000,432,21,0.0000,24,0.0000,22.8996,34.7000
32826,Chevrolet,39872,Corvette,2019,Premium,filled,0.0000,465,19,0.0000,25,0.0000,20.0270,35.4602
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36723,Lamborghini,43409,Aventador Sian Roadster,2020,Premium,filled,0.0000,861,10,0.0000,14,0.0000,10.0492,19.1669
36725,Lamborghini,43410,Aventador Sian Coupe,2020,Premium,filled,0.0000,861,10,0.0000,14,0.0000,10.0492,19.1669
36726,RUF Automobile,43411,TURBO12/CTR3/CTR ANNIVERSARY,2020,Premium,filled,0.0000,497,18,0.0000,20,0.0000,20.2300,27.6300
36727,Kia,43412,Soul Electric,2020,Electricity,201 kW AC PMSM,25.9849,0,114,29.1732,101,33.0701,185.3000,145.6000
36728,Tesla,43413,Model X Long Range Plus,2020,Electricity,193 and 205 kW AC 3-Phase,31.0865,0,105,32.1566,101,33.4644,153.4000,142.5000

In [23]:
#------------------------electricity sections down------------------------------------

In [24]:
# Electricity production from renewable sources, excluding hydroelectric (% of total)
url='https://data.worldbank.org/indicator/EG.ELC.RNWX.ZS'

#Electricity production from renewable sources, excluding hydroelectric (kWh)
url='https://data.worldbank.org/indicator/EG.ELC.RNWX.KH'

#Electricity production from oil sources (% of total)
url='https://data.worldbank.org/indicator/EG.ELC.PETR.ZS'

#Electricity production from nuclear sources (% of total)
url='https://data.worldbank.org/indicator/EG.ELC.NUCL.ZS'

#Electricity production from coal sources (% of total)
url='https://data.worldbank.org/indicator/EG.ELC.COAL.ZS'

#Electricity production from oil, gas and coal sources (% of total)
url='https://data.worldbank.org/indicator/EG.ELC.FOSL.ZS'

#Electricity production from natural gas sources (% of total)
url='https://data.worldbank.org/indicator/EG.ELC.NGAS.ZS'

#Electricity production from hydroelectric sources (% of total)
url='https://data.worldbank.org/indicator/EG.ELC.HYRO.ZS'

#------------ELECTRICITY PRODUCTION BREAKDOWN--------------------#UPPER

#Electric power transmission and distribution losses (% of output)
url='https://data.worldbank.org/indicator/EG.ELC.LOSS.ZS'

#------------ACCESS TO ELECTRICITY BREAKDOWN----------------------#LOWER

#Access to electricity (% of population)
url='https://data.worldbank.org/indicator/EG.ELC.ACCS.ZS'

#Access to electricity, urban (% of urban population)
url='https://data.worldbank.org/indicator/EG.ELC.ACCS.UR.ZS'

#Access to electricity, rural (% of rural population)
url='https://data.worldbank.org/indicator/EG.ELC.ACCS.RU.ZS'

In [25]:
#FETCHING FOR VARIOUS TABLES

elect_prod_renew_sourc_per = pd.DataFrame(wb.get_series('EG.ELC.RNWX.ZS', mrv=1))
elect_prod_renew_sourc_kwh = pd.DataFrame(wb.get_series('EG.ELC.RNWX.KH', mrv=1))
elect_prod_oil_sourc = pd.DataFrame(wb.get_series('EG.ELC.PETR.ZS', mrv=1))
elect_prod_nucl_sourc = pd.DataFrame(wb.get_series('EG.ELC.NUCL.ZS', mrv=1))
elect_prod_coal_sourc = pd.DataFrame(wb.get_series('EG.ELC.COAL.ZS', mrv=1))
elect_prod_oilgascoal_sourc = pd.DataFrame(wb.get_series('EG.ELC.FOSL.ZS', mrv=1))
elect_prod_natgas_sourc = pd.DataFrame(wb.get_series('EG.ELC.NGAS.ZS', mrv=1))
elect_prod_hydro_sourc = pd.DataFrame(wb.get_series('EG.ELC.HYRO.ZS', mrv=1))
elect_power_transm_loss = pd.DataFrame(wb.get_series('EG.ELC.LOSS.ZS', mrv=1))
elect_access = pd.DataFrame(wb.get_series('EG.ELC.ACCS.ZS', mrv=1))
elect_access_urban = pd.DataFrame(wb.get_series('EG.ELC.ACCS.UR.ZS', mrv=1))
elect_access_rural = pd.DataFrame(wb.get_series('EG.ELC.ACCS.RU.ZS', mrv=1))

In [26]:
#REMOVING COLUMNS FROM INDEXES
elect_prod_renew_sourc_per.reset_index(inplace=True)
elect_prod_renew_sourc_kwh.reset_index(inplace=True)
elect_prod_oil_sourc.reset_index(inplace=True)
elect_prod_nucl_sourc.reset_index(inplace=True)
elect_prod_coal_sourc.reset_index(inplace=True)
elect_prod_oilgascoal_sourc.reset_index(inplace=True)
elect_prod_natgas_sourc.reset_index(inplace=True)
elect_prod_hydro_sourc .reset_index(inplace=True)
elect_power_transm_loss.reset_index(inplace=True)
elect_access.reset_index(inplace=True)
elect_access_urban.reset_index(inplace=True)
elect_access_rural.reset_index(inplace=True)

In [27]:
#RENAMING VALUE COLUMNS
elect_prod_renew_sourc_per=elect_prod_renew_sourc_per.rename(columns={"EG.ELC.RNWX.ZS": "Percentage"})
elect_prod_renew_sourc_kwh=elect_prod_renew_sourc_kwh.rename(columns={"EG.ELC.RNWX.KH": "KWH"})
elect_prod_oil_sourc=elect_prod_oil_sourc.rename(columns={"EG.ELC.PETR.ZS": "Percentage"})
elect_prod_nucl_sourc=elect_prod_nucl_sourc.rename(columns={"EG.ELC.NUCL.ZS": "Percentage"})
elect_prod_coal_sourc=elect_prod_coal_sourc.rename(columns={"EG.ELC.COAL.ZS": "Percentage"})
elect_prod_oilgascoal_sourc=elect_prod_oilgascoal_sourc.rename(columns={"EG.ELC.FOSL.ZS": "Percentage"})
elect_prod_natgas_sourc = elect_prod_natgas_sourc.rename(columns={"EG.ELC.NGAS.ZS": "Percentage"})
elect_prod_hydro_sourc = elect_prod_hydro_sourc.rename(columns={"EG.ELC.HYRO.ZS": "Percentage"})
elect_power_transm_loss=elect_power_transm_loss.rename(columns={"EG.ELC.LOSS.ZS": "Percentage"})
elect_access=elect_access.rename(columns={"EG.ELC.ACCS.ZS": "Percentage"})
elect_access_urban=elect_access_urban.rename(columns={"EG.ELC.ACCS.UR.ZS": "Percentage"})
elect_access_rural=elect_access_rural.rename(columns={"EG.ELC.ACCS.RU.ZS": "Percentage"})

In [28]:
#DROPPING DUMMY COLUMNS
elect_prod_renew_sourc_per=elect_prod_renew_sourc_per.drop(columns=['Series'])
elect_prod_renew_sourc_kwh=elect_prod_renew_sourc_kwh.drop(columns=['Series'])
elect_prod_oil_sourc=elect_prod_oil_sourc.drop(columns=['Series'])
elect_prod_nucl_sourc=elect_prod_nucl_sourc.drop(columns=['Series'])
elect_prod_coal_sourc=elect_prod_coal_sourc.drop(columns=['Series'])
elect_prod_oilgascoal_sourc=elect_prod_oilgascoal_sourc.drop(columns=['Series'])
elect_prod_natgas_sourc = elect_prod_natgas_sourc.drop(columns=['Series'])
elect_prod_hydro_sourc = elect_prod_hydro_sourc.drop(columns=['Series'])
elect_power_transm_loss=elect_power_transm_loss.drop(columns=['Series'])
elect_access=elect_access.drop(columns=['Series'])
elect_access_urban=elect_access_urban.drop(columns=['Series'])
elect_access_rural=elect_access_rural.drop(columns=['Series'])

In [29]:
#elect_prod_renew_sourc_per
#elect_prod_renew_sourc_kwh
#elect_prod_oil_sourc
#elect_prod_nucl_sourc
#elect_prod_coal_sourc
#elect_prod_oilgascoal_sourc
#elect_power_transm_loss
#elect_access
#elect_access_urban
#elect_access_rural

In [30]:
result=pd.merge(elect_access, elect_access_rural, on="Country")

table_elec_access=pd.merge(result,elect_access_urban, on="Country")

table_elec_access=table_elec_access.rename(columns={"Percentage_x": "Electricity Access WW", "Percentage_y":"Electricity Access Rural" , "Percentage":"Electricity Access Urban"})

table_elec_access=table_elec_access.drop(columns=['Year','Year_y'])

table_elec_access=table_elec_access.rename(columns={"Year_x": "Year"})

In [31]:
combination=pd.merge(elect_prod_renew_sourc_per, elect_prod_oil_sourc, on="Country")

combination


combination=combination.drop(columns=['Year_y'])

combination=combination.rename(columns={"Year_x": "Year", "Percentage_y":"Oil Sources %" , "Percentage_x":"Renewable Sources %"})

combination2=pd.merge(combination, elect_prod_nucl_sourc, on="Country")

combination2=combination2.drop(columns=['Year_y'])

combination2=combination2.rename(columns={"Percentage": "Nuclear Sources %"})

combination3=pd.merge(combination2, elect_prod_coal_sourc, on="Country")

combination3=combination3.drop(columns=['Year'])

combination4=combination3.rename(columns={"Year_x": "Year", "Percentage": "Coal Sources %"})

combination5=pd.merge(combination4, elect_prod_natgas_sourc, on="Country")

combination5=combination5.drop(columns=['Year_y'])

combination5=combination5.rename(columns={"Percentage": "Natural Gas Sources %", "Year_x": "Year"})

combination6=pd.merge(combination5, elect_prod_hydro_sourc, on="Country")

combination6=combination6.drop(columns=['Year_y'])

table_elec_source_breakdown=combination6.rename(columns={"Percentage": "Hydroelectric Sources %", "Year_x": "Year"})

In [32]:
table_elec_source_breakdown

,Country,Year,Renewable Sources %,Oil Sources %,Nuclear Sources %,Coal Sources %,Natural Gas Sources %,Hydroelectric Sources %
0,Arab World,2015,0.454259,20.509818,NaN,1.519196,64.071422,2.438456
1,Caribbean small states,2015,NaN,NaN,NaN,NaN,NaN,NaN
2,Central Europe and the Baltics,2015,11.119740,0.854239,13.653417,50.344621,7.101308,9.133112
3,Early-demographic dividend,2015,3.566784,9.073565,0.264383,36.528430,32.589130,14.003280
4,East Asia & Pacific,2015,4.974811,1.681473,1.946614,59.391846,13.524058,15.228439
...,...,...,...,...,...,...,...,...
259,Virgin Islands (U.S.),2015,NaN,NaN,NaN,NaN,NaN,NaN
260,West Bank and Gaza,2015,NaN,NaN,NaN,NaN,NaN,NaN
261,"Yemen, Rep.",2015,0.000000,60.195268,NaN,0.000000,39.804732,0.000000
262,Zambia,2015,0.000000,3.006176,NaN,0.000000,0.000000,96.993824
263,Zimbabwe,2015,1.328664,0.494387,NaN,46.781337,0.000000,51.395612

In [33]:
table_elec_access

,Country,Year,Electricity Access WW,Electricity Access Rural,Electricity Access Urban
0,Arab World,2018,89.286856,79.248100,97.063959
1,Caribbean small states,2018,98.401602,97.226735,99.584314
2,Central Europe and the Baltics,2018,100.000000,100.000000,99.994298
3,Early-demographic dividend,2018,90.724652,84.200218,98.793351
4,East Asia & Pacific,2018,97.986434,96.344871,99.081422
...,...,...,...,...,...
259,Virgin Islands (U.S.),2018,100.000000,100.000000,100.000000
260,West Bank and Gaza,2018,100.000000,100.000000,100.000000
261,"Yemen, Rep.",2018,62.000000,48.698349,85.000000
262,Zambia,2018,39.812622,10.968000,77.245483
263,Zimbabwe,2018,41.041584,19.997750,85.333015

In [34]:
#car = input("what is your car ?"):
#    if car in cars2018_c["brand"]:
#        cars["model"][cars2018_c["model"] == car]
#        
#        model= input(what model?)
#region = input( "do you drive more in the city or highway or both")        
#

In [35]:
cars2018_c["model"][cars2018_c["brand"] == "Jeep"]

32814                    Cherokee FWD
32815                    Cherokee 4WD
32816    Cherokee 4WD Active Drive II
32817          Cherokee Trailhawk 4WD
32846                    Cherokee FWD
                     ...
36452              Grand Cherokee 2WD
36454              Grand Cherokee 4WD
36455              Grand Cherokee 4WD
36710                    Renegade 4WD
36714          Grand Cherokee SRT 4WD
Name: model, Length: 99, dtype: object

In [36]:
cars2018_c["model"][cars2018_c["brand"] == "Jeep"].unique()

array(['Cherokee FWD', 'Cherokee 4WD', 'Cherokee 4WD Active Drive II',
       'Cherokee Trailhawk 4WD', 'Compass FWD', 'Compass 4WD',
       'Grand Cherokee 2WD', 'Grand Cherokee 4WD',
       'Grand Cherokee SRT 4WD', 'Grand Cherokee Trackhawk 4WD',
       'Wrangler 4WD', 'Wrangler Unlimited 4WD', 'Renegade 2WD',
       'Renegade 4WD', 'Renegade Trailhawk 4WD', 'Gladiator Pickup 4WD',
       'Wrangler 2dr 4WD', 'Wrangler 4dr 4WD', 'Gladiator 4WD',
       'Wrangler 4dr EcoDiesel 4WD', 'Wrangler Rubic 4dr EcoDiesel 4WD',
       'Gladiator EcoDiesel 4WD', 'Gladiator Rubicon EcoDiesel 4WD'],
      dtype=object)

In [37]:
cars2018_c

,brand,id,model,year,fueltype,evMotor,City_kwh_100km,CO2_gperkm,combined_lperkm,combined_kwh_100km,highway08,highway_kwh_100km,City_lperkm,UHighway
32814,Jeep,39861,Cherokee FWD,2019,Midgrade,filled,0.0000,387,23,0.0000,29,0.0000,24.9000,40.9961
32815,Jeep,39862,Cherokee 4WD,2019,Midgrade,filled,0.0000,400,22,0.0000,27,0.0000,24.2000,38.8000
32816,Jeep,39863,Cherokee 4WD Active Drive II,2019,Midgrade,filled,0.0000,416,21,0.0000,26,0.0000,23.1000,37.0483
32817,Jeep,39864,Cherokee Trailhawk 4WD,2019,Midgrade,filled,0.0000,432,21,0.0000,24,0.0000,22.8996,34.7000
32826,Chevrolet,39872,Corvette,2019,Premium,filled,0.0000,465,19,0.0000,25,0.0000,20.0270,35.4602
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36723,Lamborghini,43409,Aventador Sian Roadster,2020,Premium,filled,0.0000,861,10,0.0000,14,0.0000,10.0492,19.1669
36725,Lamborghini,43410,Aventador Sian Coupe,2020,Premium,filled,0.0000,861,10,0.0000,14,0.0000,10.0492,19.1669
36726,RUF Automobile,43411,TURBO12/CTR3/CTR ANNIVERSARY,2020,Premium,filled,0.0000,497,18,0.0000,20,0.0000,20.2300,27.6300
36727,Kia,43412,Soul Electric,2020,Electricity,201 kW AC PMSM,25.9849,0,114,29.1732,101,33.0701,185.3000,145.6000
36728,Tesla,43413,Model X Long Range Plus,2020,Electricity,193 and 205 kW AC 3-Phase,31.0865,0,105,32.1566,101,33.4644,153.4000,142.5000

In [38]:
cars2018_c=cars2018_c.reset_index()
cars2018_c=cars2018_c.drop(columns='index')
cars2018_c['Brand & Model'] = cars2018_c['brand'] + ' ' + cars2018_c['model']
cars2018_c

,brand,id,model,year,fueltype,evMotor,City_kwh_100km,CO2_gperkm,combined_lperkm,combined_kwh_100km,highway08,highway_kwh_100km,City_lperkm,UHighway,Brand & Model
0,Jeep,39861,Cherokee FWD,2019,Midgrade,filled,0.0000,387,23,0.0000,29,0.0000,24.9000,40.9961,Jeep Cherokee FWD
1,Jeep,39862,Cherokee 4WD,2019,Midgrade,filled,0.0000,400,22,0.0000,27,0.0000,24.2000,38.8000,Jeep Cherokee 4WD
2,Jeep,39863,Cherokee 4WD Active Drive II,2019,Midgrade,filled,0.0000,416,21,0.0000,26,0.0000,23.1000,37.0483,Jeep Cherokee 4WD Active Drive II
3,Jeep,39864,Cherokee Trailhawk 4WD,2019,Midgrade,filled,0.0000,432,21,0.0000,24,0.0000,22.8996,34.7000,Jeep Cherokee Trailhawk 4WD
4,Chevrolet,39872,Corvette,2019,Premium,filled,0.0000,465,19,0.0000,25,0.0000,20.0270,35.4602,Chevrolet Corvette
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3412,Lamborghini,43409,Aventador Sian Roadster,2020,Premium,filled,0.0000,861,10,0.0000,14,0.0000,10.0492,19.1669,Lamborghini Aventador Sian Roadster
3413,Lamborghini,43410,Aventador Sian Coupe,2020,Premium,filled,0.0000,861,10,0.0000,14,0.0000,10.0492,19.1669,Lamborghini Aventador Sian Coupe
3414,RUF Automobile,43411,TURBO12/CTR3/CTR ANNIVERSARY,2020,Premium,filled,0.0000,497,18,0.0000,20,0.0000,20.2300,27.6300,RUF Automobile TURBO12/CTR3/CTR ANNIVERSARY
3415,Kia,43412,Soul Electric,2020,Electricity,201 kW AC PMSM,25.9849,0,114,29.1732,101,33.0701,185.3000,145.6000,Kia Soul Electric
3416,Tesla,43413,Model X Long Range Plus,2020,Electricity,193 and 205 kW AC 3-Phase,31.0865,0,105,32.1566,101,33.4644,153.4000,142.5000,Tesla Model X Long Range Plus

In [39]:
#------------------------------------------FUNCTIONS-START------------------------------------------#
def habit_decision():
    habit_driving = input('Where do you usally drive? City, Highway or Both?')
    habit_driving = habit_driving.lower()
    
    while (habit_driving != 'city')&(habit_driving != 'highway')&(habit_driving != 'both'):
        print('Spell it decently please...')
        habit_driving = input('Where do you usally drive? City, Highway or Both?')
               
    
    car_decision_making()
    
#------------------------------------------FUNCTIONS------------------------------------------#
    
def country_decision_making():

    country_decision1 = input('Pick a country for analysis?')
    while (table_elec_source_breakdown['Country'] == country_decision1).any() == False:
        print('Spell it decently please...')
        country_decision1 = input('Pick a country for analysis?')
    
    country_decision2 = input('Do you want to pick another country?(Y) or (N)')
    while (country_decision2 != 'Y')&(country_decision2 != 'N'):
        country_decision2 = input('Do you want to pick another car?(Y) or (N)')
    
    if country_decision2 == 'Y':
        country2 = input('Pick another country?')
        while (table_elec_source_breakdown['Country'] == country2).any() == False:
            print('Spell it decently please...')
            
        country_decision3 = input('Do you want to pick another country?(Y) or (N)')
        while (country_decision3 != 'Y')&(country_decision3 != 'N'):
            country_decision3 = input('Do you want to pick another car?(Y) or (N)')
        
        if country_decision3 == 'Y':
            country_decision3 = input('Pick another country?')
            while (table_elec_source_breakdown['Country'] == country_decision3).any() == False:
                print('Spell it decently please...') 
                country_decision3 = input('Pick another country?')
            habit_decision() 
            
    elif country_decision2 == 'N':
        habit_decision()
    habit_decision()

#------------------------------------------FUNCTIONS------------------------------------------#
    
def car_decision_making():

    brand_decision1 = input('Pick a brand car for analysis?')
    while (cars2018_c['brand'] == brand_decision1).any() == False:
        print('Spell it decently please...')
        brand_decision1 = input('Pick a brand car for analysis?')
        
    #cars2018_c['model'].unique() SHOW THE MODEL LIST FOR THAT PARTICULAR BRAND
    
    model_decision1 = input('Pick a model for your ' + brand_decision1 + '!')
    while (cars2018_c['model'] == model_decision1).any() == False:
        print('Spell it decently please...')
        model_decision1 = input('Pick a model for your ' + brand_decision1 + '!')
    car_choice1 = brand_decision1 +' '+ model_decision1
   
    more_cars1 = input('Do you want to pick another car?(Y) or (N)')
    while (more_cars1 != 'Y')&(more_cars1 != 'N'):
        more_cars1 = input('Do you want to pick another car?(Y) or (N)')
    
    if more_cars1 == 'Y':
        brand_decision2 = input('Pick a brand car for analysis?')
        while (cars2018_c['brand'] == brand_decision2).any() == False:
            print('Spell it decently please...')
            brand_decision2 = input('Pick a brand car for analysis?')
        #cars2018_c['model'].unique() SHOW THE MODEL LIST FOR THAT PARTICULAR BRAND
        model_decision2 = input('Pick a model for your ' + brand_decision2 + '!')
        while (cars2018_c['model'] == model_decision2).any() == False:
            print('Spell it decently please...')
            model_decision2 = input('Pick a model for your ' + brand_decision2 + '!')
        car_choice1 = brand_decision2 +' '+ model_decision2
        
        more_cars2 = input('Do you want to pick another car?(Y) or (N)')
        while (more_cars2 != 'Y')&(more_cars2 != 'N'):
            more_cars2 = input('Do you want to pick another car?(Y) or (N)')
        
        if more_cars2 == 'Y':
            brand_decision3 = input('Pick a brand car for analysis?')
            while (cars2018_c['brand'] == brand_decision3).any() == False:
                print('Spell it decently please...')
                brand_decision3 = input('Pick a brand car for analysis?')
            #cars2018_c['model'].unique() SHOW THE MODEL LIST FOR THAT PARTICULAR BRAND
            model_decision3 = input('Pick a model for your ' + brand_decision3 + '!')
            while (cars2018_c['model'] == model_decision3).any() == False:
                print('Spell it decently please...')
                model_decision3 = input('Pick a model for your ' + brand_decision3 + '!')
            car_choice1 = brand_decision3 +' '+ model_decision3
    elif more_cars1 == 'N':
        result_dataframe()
    
    
def result_dataframe():
    print('dataframe')

def play_product():
    print('Welcome to our analysis, where we help you make your own decision based on facts!')
    country_decision_making()
#------------------------------------------FUNCTIONS-END------------------------------------------#

In [40]:
#habits= input("where do usually drive? city, highway or both ?) 
#car = input("what conventional vehicle would you like to buy ?")
#              
#if car in cars2018_c["brand"]:
#
#    cars["model"][cars2018_c["brand"] == car]
#
#    model= input("what model would you chose from those listed above ?")
#    co2emission=cars2018_c["CO2_gperkm"][cars2018_c["model"]==model
#    print("the co2 emission for the car you chose equals "+ co2emission + " per kilometers")
#
#region = input( "do you drive more in the city or highway or both")
#
##for the electrical vehicle input 
#elec_car = input("what electrical vehicle would you like to buy?")
#if elec_car in cars2018_c["brand"]:
#
#   cars["model"][cars2018_c["brand"] == car]
#
#   model= input("what model would you chose from those listed above ?")
#   habits= input("where do usually drive? city, highway or both ?)
#

In [41]:
table_elec_source_breakdown['Country']

0                          Arab World
1              Caribbean small states
2      Central Europe and the Baltics
3          Early-demographic dividend
4                 East Asia & Pacific
                    ...
259             Virgin Islands (U.S.)
260                West Bank and Gaza
261                       Yemen, Rep.
262                            Zambia
263                          Zimbabwe
Name: Country, Length: 264, dtype: object

In [42]:
#list of models printing after brand picked

#cars2018_c['brand']
#list(cars2018_c['model'].unique())

In [43]:
play_product()

Welcome to our analysis, where we help you make your own decision based on facts!
Pick a country for analysis?Portugal
Do you want to pick another country?(Y) or (N)N
Where do you usally drive? City, Highway or Both?City
Pick a brand car for analysis?Tesla
Pick a model for your Tesla!Model X Long Range Plus
Do you want to pick another car?(Y) or (N)N
dataframe